### ISSUE TITLE
I'm not too sure what I'm looking at. Could you possibly add comments in your code please so its easier to integrate into our own code

### ISSUE THREAD

**Issue by alexjshepler** [stqcky/Twitchifier#1]

**Comment by stqcky** [comment]
This is not a library of some sort that you add in your own project, it's just an app. If you want some help with adding some of my code to your project reply with what you need help with.

**Comment by alexjshepler** [comment]
So, I'm trying to make a discord bot and I'm mainly intrested in the notifications part

**Comment by stqcky** [comment]
Check this out: https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.notifyicon?view=net-5.0

**Comment by alexjshepler** [comment]
Hi, sorry for not clarifying. I just need to hook into the event when somone went live. I'm not trying to post notifications to the desktop. I'm making a bot for discord that would notify that server in a specific channel when someone went live.

**Comment by stqcky** [comment]
I'm using this lib (https://github.com/TwitchLib/TwitchLib) to check if someone is live or not.
